DEVICE_PATH := device/blackshark/klein

# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true

# A/B Partitioning
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS += \
    odm \
    system \
    product \
    system_ext \
    vendor
BOARD_USES_RECOVERY_AS_BOOT := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := kryo300

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_VARIANT := cortex-a75

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := klein
TARGET_NO_BOOTLOADER := true

# Display
TARGET_SCREEN_DENSITY := 440

# Kernel
BOARD_BOOTIMG_HEADER_VERSION := 2
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_CMDLINE := console=ttyMSM0,115200n8 androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 androidboot.usbcontroller=a600000.dwc3 swiotlb=2048 loop.max_part=7 cgroup.memory=nokmem,nosocket reboot=panic_warm androidboot.selinux=permissive androidboot.usbconfigfs=true
BOARD_KERNEL_PAGESIZE := 4096
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_KERNEL_SEPARATED_DTBO := true
TARGET_KERNEL_CONFIG := klein_defconfig
TARGET_KERNEL_SOURCE := kernel/blackshark/klein

# Kernel - Prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)
BOARD_INCLUDE_DTB_IN_BOOTIMG := false
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
BOARD_KERNEL_SEPARATED_DTBO := false
endif

# Partitions
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_BOOTIMAGE_PARTITION_SIZE := 104857600
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 104857600
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := blackshark_dynamic_partitions
BOARD_BLACKSHARK_DYNAMIC_PARTITIONS_PARTITION_LIST := system system_ext product vendor odm
BOARD_BLACKSHARK_DYNAMIC_PARTITIONS_SIZE := 9122611200

# Platform
TARGET_BOARD_PLATFORM := kona

# Recovery
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Security Patch Levels
PLATFORM_SECURITY_PATCH := 2021-08-01
VENDOR_SECURITY_PATCH := 2021-08-01
PLATFORM_VERSION := 11.0

# Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3

# OrangeFox Configuration
# Maintainer Info
OF_MAINTAINER := "Your Name"

# Build Info
FOX_VERSION := "R11.1_0"
FOX_BUILD_TYPE := "Unofficial"

# Device Info
TARGET_DEVICE_ALT := "KLE-H0"

# Features
OF_USE_MAGISKBOOT := true
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := true
OF_USE_NEW_MAGISKBOOT := true
OF_DONT_PATCH_ENCRYPTED_DEVICE := true
OF_NO_TREBLE_COMPATIBILITY_CHECK := true
OF_USE_SYSTEM_FINGERPRINT := true
OF_SKIP_MULTIUSER_FOLDERS_BACKUP := true

# Screen Settings
OF_SCREEN_H := 2400
OF_STATUS_H := 80
OF_NAVIGATION_BAR_H := 120

# OTA & MIUI
OF_KEEP_DM_VERITY := true
OF_KEEP_FORCED_ENCRYPTION := true
OF_SUPPORT_ALL_BLOCK_OTA_UPDATES := true
OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR := true
OF_VANILLA_BUILD := false

# Language and Theme
OF_TRANSLATE_ENGLISH := true
OF_USE_TWRP_SAR_DETECT := true
FOX_REPLACE_BUSYBOX_PS := true
FOX_USE_BASH_SHELL := true
FOX_USE_NANO_EDITOR := true
FOX_DELETE_AROMAFM := true
FOX_ENABLE_APP_MANAGER := true

# Disable unused features
TARGET_DISABLE_GRAMFS := true
